In [42]:
# Elizabeth Wu vcn2fj
# ACC Basketball HW Assignment

# Note: the reflection is included at the end as a markdown file

In [55]:
# !git clone https://github.com/vcn2fj/DS2002F24

In [44]:
# 1
import pandas as pd

# Load the regular season and playoff data (semicolon-separated and encoding handled)
df = pd.read_csv('/content/DS2002F24/homework/acc_players-2324F.csv', sep=',', encoding='latin1', skiprows=[0]) # skipping first row because they are not useful headings

display(df.head(5)) # displaying first five rows

,Rk,Player,Class,Pos,School,G,MP,TRB,AST,STL,...,TOV,PF,PTS,FG%,2P%,3P%,FT%,PER,WS,BPM
0,1,Amaree Abram,SO,G,Georgia Tech,10,108,17,11,1,...,9,10,34,0.262,0.318,0.200,0.615,4.1,-0.1,-6.4
1,2,Sola Adebisi,FR,F,Florida State,7,9,1,1,0,...,1,1,2,0.500,0.500,NaN,NaN,3.5,0.0,-6.7
2,3,Prince Aligbe,SO,F,Boston College,35,651,119,21,15,...,30,51,164,0.435,0.522,0.147,0.620,9.4,0.9,-1.3
3,4,Abe Atiyeh,SR,G,Boston College,4,6,0,0,0,...,1,0,3,0.333,0.000,1.000,NaN,1.1,0.0,-8.2
4,5,Zack Austin,JR,F,Pittsburgh,33,746,137,29,32,...,13,35,216,0.417,0.563,0.295,0.737,18.0,2.9,7.9

In [45]:
# 2
# total points scored by all players
total = df['PTS'].sum()
print(total)

38411

In [46]:
# player with most minutes
df['Player'].iloc[df['MP'].idxmax()]

'Casey Morsell'

In [47]:
# top 5 players in terms of total rebounds
df.nlargest(5, 'TRB')['Player']

5        Armando Bacot
178    Ian Schieffelin
90     Harrison Ingram
44      Mohamed Diarra
149      Norchad Omier
Name: Player, dtype: object

In [48]:
# 3
# creating new df containing only players who played more than 500 min
df_new = df[df['MP'] > 500]
df_new.head()

,Rk,Player,Class,Pos,School,G,MP,TRB,AST,STL,...,TOV,PF,PTS,FG%,2P%,3P%,FT%,PER,WS,BPM
2,3,Prince Aligbe,SO,F,Boston College,35,651,119,21,15,...,30,51,164,0.435,0.522,0.147,0.620,9.4,0.9,-1.3
4,5,Zack Austin,JR,F,Pittsburgh,33,746,137,29,32,...,13,35,216,0.417,0.563,0.295,0.737,18.0,2.9,7.9
5,6,Armando Bacot,SR,F,North Carolina,37,1123,380,56,22,...,60,100,538,0.540,0.544,0.400,0.781,24.6,6.1,8.9
7,8,Reece Beekman,SR,G,Virginia,34,1114,124,212,68,...,70,43,486,0.443,0.487,0.310,0.754,23.4,4.9,10.5
9,10,Chris Bell,SO,F,Syracuse,32,865,75,21,18,...,26,58,384,0.434,0.459,0.420,0.842,14.9,2.2,3.3

In [49]:
# determining player with the highest total assists
df_new['Player'].iloc[df_new['AST'].idxmax()]

'Maliq Brown'

In [50]:
# top 3 assist leads in league (using unfiltered df)
df.nlargest(3, 'AST')['Player']

7       Reece Beekman
215    Jaeden Zackery
21      Elliot Cadeau
Name: Player, dtype: object

In [51]:
# top 3 shot blockers (using unfiltered df)
df.nlargest(3, 'BLK')['Player']

51         Ryan Dunn
157     Quinten Post
5      Armando Bacot
Name: Player, dtype: object

In [52]:
# 4
# total points scored by each school
df_school = df.groupby('School')[['PTS']].sum().reset_index()
df_school

            School   PTS
0   Boston College  2667
1          Clemson  2785
2             Duke  2830
3    Florida State  2526
4     Georgia Tech  2272
5       Louisville  2304
6       Miami (FL)  2424
7         NC State  3101
8   North Carolina  3032
9       Notre Dame  2113
10      Pittsburgh  2495
11        Syracuse  2442
12        Virginia  2140
13   Virginia Tech  2547
14     Wake Forest  2733

In [53]:
# total assists for each school
df_ast = df.groupby('School')[['AST']].sum().reset_index()
df_ast

            School  AST
0   Boston College  509
1          Clemson  533
2             Duke  551
3    Florida State  406
4     Georgia Tech  425
5       Louisville  356
6       Miami (FL)  454
7         NC State  536
8   North Carolina  536
9       Notre Dame  335
10      Pittsburgh  452
11        Syracuse  442
12        Virginia  509
13   Virginia Tech  514
14     Wake Forest  429

In [54]:
# sort schools by total pts scored and display top 3 schools
df_school.nlargest(3, 'PTS')['School']

7          NC State
8    North Carolina
2              Duke
Name: School, dtype: object

## Reflection:
When working with CSV files, I learned the importance of previewing the data before beginning any manipulation. By using the head.() function, I was able to confirm that I had imported the csv file correctly into a pandas dataframe. I noticed two headers present, the first of which was not necessarily useful for this assignment, so I dropped it. Filtering through the data improved my understanding of the structure and columns of the dataframe, leading to more accurate analysis. Moving forward with future data analysis projects, I plan to view the data frame and incorporate summary statistics to gain a deeper understanding of the datasets I work with.

The most challenging aspect of this assignment was to group the data frame by specific columns and then perform basic analyses. Because this was a multistep process, I occasionally miswrote the code or performed the functions in the incorrect order. To address these challenges, I used both the in-class notebooks and online resources focused on pandas to debug my code. Additionally, I encountered difficulties understanding some of the column names but a quick google search revealed what the acronyms stood for.

The insights gained from analyzing ACC basketball statistics could be applied to the field of healthcare. For instance, a relevant dataset might include information about COVID-19 cases in the U.S. Similar to how I grouped players by school to calculate total points scored, one could group individuals by regions in Virginia to determine the total number of Covid cases requiring hospitalization. This assignment was beneficial, as the analyses performedâ€”such as filtering, grouping, and calculating totalsâ€”can be valuable across various datasets and fields when applied correctly.